data = data = [
    {"name": "Instagram", "follower_count": 651, "description": "Social media platform", "country": "United States"},
    {"name": "Cristiano Ronaldo", "follower_count": 631, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 504, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 430, "description": "Musician and actress", "country": "United States"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Reality TV personality and businesswoman", "country": "United States"},
    {"name": "Dwayne Johnson", "follower_count": 397, "description": "Actor and professional wrestler", "country": "United States"},
    {"name": "Ariana Grande", "follower_count": 390, "description": "Musician and actress", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 363, "description": "Reality TV personality and businesswoman", "country": "United States"},
    {"name": "Beyoncé", "follower_count": 319, "description": "Musician", "country": "United States"},
    {"name": "Nike", "follower_count": 310, "description": "Sportswear brand", "country": "United States"},
    {"name": "Justin Bieber", "follower_count": 294, "description": "Musician", "country": "Canada"},
    {"name": "Kendall Jenner", "follower_count": 292, "description": "Model and TV personality", "country": "United States"},
    {"name": "National Geographic", "follower_count": 282, "description": "Magazine and media company", "country": "United States"},
    {"name": "Taylor Swift", "follower_count": 278, "description": "Musician", "country": "United States"},
    {"name": "Jennifer Lopez", "follower_count": 252, "description": "Singer and actress", "country": "United States"},
    {"name": "Virat Kohli", "follower_count": 270, "description": "Cricketer", "country": "India"},
    {"name": "NASA", "follower_count": 159, "description": "Space agency", "country": "United States"},
    {"name": "Zendaya", "follower_count": 190, "description": "Actress and singer", "country": "United States"},
    {"name": "Emma Watson", "follower_count": 75, "description": "Actress and activist", "country": "United Kingdom"},
    {"name": "Shakira", "follower_count": 90, "description": "Singer and dancer", "country": "Colombia"}
]